openapi: 3.0.0
info:
  version: 0.1.0
  title: Inquira API
  description: Documentation for the Inquira API
servers:
  - url: v1
components:
  schemas: {}
  parameters: {}
paths:
  /deployments:
    get:
      summary: List all deployments
      description: Lists all deployments including active and inactive ones.
      parameters:
        - schema:
            type: string
            enum:
              - "true"
              - "false"
            description: Filter deployments by active status. If not provided, returns all
              deployments.
          required: false
          name: active
          in: path
        - schema:
            type: string
            enum:
              - inbound
              - outbound
            description: Filter deployments by call type. If not provided, returns all
              types.
          required: false
          name: type
          in: path
      responses:
        "200":
          description: Object with deployment data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  deployments:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier for the deployment
                        start_at:
                          type: string
                          format: date-time
                          description: ISO timestamp when the deployment starts
                        end_by:
                          type: string
                          nullable: true
                          format: date-time
                          description: ISO timestamp when the deployment should end
                        stopped_at:
                          type: string
                          nullable: true
                          format: date-time
                          description: ISO timestamp when the deployment was stopped, null if still active
                        call_type:
                          type: string
                          enum:
                            - inbound
                            - outbound
                          description: Type of deployment - either inbound or outbound calls
                        workflow_release_id:
                          type: string
                          format: uuid
                          description: ID of the workflow release associated with the deployment
                      required:
                        - id
                        - start_at
                        - end_by
                        - stopped_at
                        - call_type
                        - workflow_release_id
                    description: Array of deployment objects
                required:
                  - deployments
        "400":
          description: Bad Request - Invalid input parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Validation error message
        "401":
          description: Unauthorized - Invalid or missing API key
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Authentication error message
        "403":
          description: Forbidden - Team is inactive or lacks permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Authorization error message
        "404":
          description: Not Found - Requested resource does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Resource not found message
        "422":
          description: Unprocessable Entity - Input validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                        message:
                          type: string
                        code:
                          type: string
                      required:
                        - field
                        - message
                        - code
                required:
                  - error
                  - details
                description: Validation error details
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Internal server error message
  /workflows:
    get:
      summary: List all workflows
      description: Lists all workflows including active and inactive ones.
      responses:
        "200":
          description: Object with workflow data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  workflows:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          format: uuid
                          description: Unique identifier for the workflow release
                        name:
                          type: string
                          description: Name of the workflow release
                        created_at:
                          type: string
                          format: date-time
                          description: When the release was created
                        status:
                          type: string
                          enum:
                            - released
                            - development
                          description: Status of the workflow - either released or in development
                      required:
                        - id
                        - name
                        - created_at
                        - status
                    description: Array of workflow releases
                required:
                  - workflows
        "400":
          description: Bad Request - Invalid input parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Validation error message
        "401":
          description: Unauthorized - Invalid or missing API key
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Authentication error message
        "403":
          description: Forbidden - Team is inactive or lacks permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Authorization error message
        "404":
          description: Not Found - Requested resource does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Resource not found message
        "422":
          description: Unprocessable Entity - Input validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                        message:
                          type: string
                        code:
                          type: string
                      required:
                        - field
                        - message
                        - code
                required:
                  - error
                  - details
                description: Validation error details
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Internal server error message
  /workflows/{workflow_id}:
    get:
      summary: Get workflow details
      description: Get workflow details by its ID.
      responses:
        "200":
          description: Object with workflow data.
          content:
            application/json:
              schema:
                type: object
                properties:
                  workflow:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                        description: Unique identifier for the workflow
                      name:
                        type: string
                        description: Name of the workflow
                      created_at:
                        type: string
                        format: date-time
                        description: When the workflow was created
                      status:
                        type: string
                        enum:
                          - released
                          - development
                        description: Status of the workflow
                      language:
                        type: string
                        description: Language of the workflow
                      input_schema:
                        type: object
                        properties:
                          properties:
                            type: object
                            additionalProperties:
                              type: object
                              properties:
                                type:
                                  type: string
                                  enum:
                                    - string
                                    - number
                                    - boolean
                                  description: |
                                    Data type of the field. Possible values:
                                    - string: Text input
                                    - number: Numeric input
                                    - boolean: True/false input
                                format:
                                  type: string
                                  enum:
                                    - tel
                                    - date-time
                                    - date
                                    - time
                                    - email
                                  description: >-
                                    Special format of the field. Possible
                                    values:

                                    - tel: Phone number in E.164 format e.g
                                    +31123123123 

                                    - date-time: Date and time in ISO 8601
                                    format

                                    - date: Date in ISO 8601 format

                                    - time: Time in 24-hour format e.g 23:59 

                                    - email: Email address e.g john@doe.com
                                title:
                                  type: string
                                  description: Display title for the field
                                description:
                                  type: string
                                  description: Detailed description of the field
                              required:
                                - type
                                - title
                                - description
                              description: Definition of a form field
                            description: Field definitions
                        required:
                          - properties
                        description: Schema defining required inputs for the workflow
                        example:
                          properties:
                            user_first_name:
                              type: string
                              title: First Name
                              description: The patient's first name.
                      phone_number_key:
                        type: string
                        description: Key for the phone number input field
                    required:
                      - id
                      - name
                      - created_at
                      - status
                      - language
                      - input_schema
                      - phone_number_key
                    description: Detailed workflow information
                required:
                  - workflow
        "400":
          description: Bad Request - Invalid input parameters
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Validation error message
        "401":
          description: Unauthorized - Invalid or missing API key
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Authentication error message
        "403":
          description: Forbidden - Team is inactive or lacks permissions
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Authorization error message
        "404":
          description: Not Found - Requested resource does not exist
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Resource not found message
        "422":
          description: Unprocessable Entity - Input validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  details:
                    type: array
                    items:
                      type: object
                      properties:
                        field:
                          type: string
                        message:
                          type: string
                        code:
                          type: string
                      required:
                        - field
                        - message
                        - code
                required:
                  - error
                  - details
                description: Validation error details
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                required:
                  - error
                description: Internal server error message
